CREATE TABLE "koalas_info" (
	"id" SERIAL PRIMARY KEY,
	"Name" VARCHAR (250) NOT NULL,
	"Age" INTEGER NOT NULL,
	"Gender" VARCHAR (1) NOT NULL,
    "Transfer Status" BOOLEAN DEFAULT FALSE,
    "Notes" VARCHAR (250) NOT NULL
);


